version: "3.8"
services:
  mongodb:
    image: mongo:5.0.6
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=mydatabase
    ports:
      - "27017:27017"
    volumes:
      - ./tmpdata/mongodb_data:/data/db
    networks:
      - node-webapp-network
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    networks:
      - node-webapp-network
networks:
  node-webapp-network:
    driver: bridge

